import { TemplateTheme, TemplateId } from '../types';

export const TEMPLATE_THEMES: Record<TemplateId, TemplateTheme> = {
  thpt_national: {
    id: 'thpt_national',
    name: 'Chuẩn Bộ GD&ĐT (Đề Thi THPT Quốc Gia)',
    badgeTitle: 'Chuẩn Bộ GD&ĐT',
    description: 'Khung viền đôi chuẩn mực, bố trí mã đề thi, bảng phiếu tô trắc nghiệm và thông tin phòng thi.',
    primaryColor: '#0f172a', // slate-900
    primaryBg: '#ffffff',
    accentColor: '#1e3a8a', // blue-900
    headerBg: 'bg-slate-900 text-white',
    headerText: 'text-slate-900',
    cardBorder: 'border-slate-900',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-slate-900 text-white font-bold px-2.5 py-0.5 rounded-none border border-slate-700',
    lineColor: '#334155',
    icon: 'GraduationCap',
    bannerGradient: 'from-slate-950 via-slate-900 to-zinc-900',
    variant: 'classic_academic',
  },
  olympiad_royal: {
    id: 'olympiad_royal',
    name: 'Chuyên Toán & Olympic (Royal Navy & Gold)',
    badgeTitle: 'Chuyên Toán & Olympic',
    description: 'Tông Xanh Hải quân đậm kết hợp Vàng Kim vương giả, viền kép góc cạnh, huy hiệu sao toán học.',
    primaryColor: '#1e3a8a', // blue-900
    primaryBg: '#f8fafc',
    accentColor: '#d97706', // amber-600
    headerBg: 'bg-gradient-to-r from-blue-950 via-indigo-950 to-blue-900 text-white',
    headerText: 'text-blue-950',
    cardBorder: 'border-blue-900',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-blue-900 text-white font-bold px-3 py-1 rounded-lg shadow-xs border border-amber-400',
    lineColor: '#60a5fa',
    icon: 'Trophy',
    bannerGradient: 'from-blue-950 via-indigo-900 to-amber-700',
    variant: 'square_frame',
  },
  stem_emerald: {
    id: 'stem_emerald',
    name: 'Khoa Học & STEM (Emerald Tech Grid)',
    badgeTitle: 'Khoa Học & STEM',
    description: 'Nền chìm họa tiết hệ trục tọa độ Oxy và khối không gian 3D, xanh ngọc Emerald công nghệ hiện đại.',
    primaryColor: '#059669', // emerald-600
    primaryBg: '#f0fdf4',
    accentColor: '#0891b2', // cyan-600
    headerBg: 'bg-gradient-to-r from-emerald-900 via-teal-900 to-cyan-950 text-white',
    headerText: 'text-emerald-950',
    cardBorder: 'border-emerald-700',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-emerald-700 text-white font-mono px-3 py-0.5 rounded-md shadow-xs',
    lineColor: '#10b981',
    icon: 'Atom',
    bannerGradient: 'from-emerald-800 via-teal-800 to-cyan-900',
    variant: 'math_watermark',
  },
  ams_latex: {
    id: 'ams_latex',
    name: 'Hàn Lâm AMS-LaTeX (Monochrome Classic)',
    badgeTitle: 'AMS-LaTeX Classic',
    description: 'Phong cách tạp chí Toán học Quốc tế AMS, tối giản đen trắng sắc nét, tối ưu hóa mực in và trang.',
    primaryColor: '#18181b', // zinc-900
    primaryBg: '#ffffff',
    accentColor: '#3f3f46',
    headerBg: 'bg-zinc-900 text-white',
    headerText: 'text-zinc-900',
    cardBorder: 'border-zinc-900',
    fontFamily: 'stix_math',
    badgeStyle: 'bg-zinc-900 text-white font-serif px-2.5 py-0.5 rounded-none',
    lineColor: '#71717a',
    icon: 'BookOpen',
    bannerGradient: 'from-zinc-900 to-slate-900',
    variant: 'square_frame',
  },
  floral_pedagogical: {
    id: 'floral_pedagogical',
    name: 'Sư Phạm Trang Nhã (Pastel Rose & Amber)',
    badgeTitle: 'Sư Phạm Trang Nhã',
    description: 'Khung hoa văn góc dịu dàng, đường nét tròn mềm mại, tạo tâm lý thoải mái, tích cực cho học sinh.',
    primaryColor: '#e11d48', // rose-600
    primaryBg: '#fff1f2',
    accentColor: '#f59e0b', // amber-500
    headerBg: 'bg-gradient-to-r from-rose-500 via-pink-500 to-amber-500 text-white',
    headerText: 'text-rose-900',
    cardBorder: 'border-rose-200',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-rose-500 text-white font-bold px-3 py-1 rounded-full shadow-xs',
    lineColor: '#fb7185',
    icon: 'HeartHandshake',
    bannerGradient: 'from-rose-500 via-pink-500 to-amber-500',
    variant: 'floral_frame',
  },
  royal_violet: {
    id: 'royal_violet',
    name: 'Tím Hoàng Gia (Royal Violet Luxury)',
    badgeTitle: 'Tím Hoàng Gia',
    description: 'Tông tím hoàng gia sang trọng, viền dải ruy-băng ánh kim, hoàn hảo cho đề kiểm tra định kỳ học kỳ.',
    primaryColor: '#6b21a8', // purple-800
    primaryBg: '#faf5ff',
    accentColor: '#9333ea', // purple-600
    headerBg: 'bg-gradient-to-r from-purple-950 via-indigo-950 to-purple-900 text-white',
    headerText: 'text-purple-950',
    cardBorder: 'border-purple-300',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-purple-900 text-white font-bold px-3 py-1 rounded-xl shadow-xs',
    lineColor: '#c084fc',
    icon: 'Crown',
    bannerGradient: 'from-purple-950 via-indigo-900 to-purple-800',
    variant: 'math_watermark',
  },
  sunset_gold: {
    id: 'sunset_gold',
    name: 'Hoàng Hôn Vinh Danh (Sunset Gold & Amber)',
    badgeTitle: 'Hoàng Hôn Vinh Danh',
    description: 'Tông Vàng Hoàng Kim & Cam ấm áp quý phái, viền kép ruy-băng trang trọng vinh danh bài tập xuất sắc.',
    primaryColor: '#c2410c', // orange-700
    primaryBg: '#fff7ed',
    accentColor: '#b45309', // amber-700
    headerBg: 'bg-gradient-to-r from-amber-600 via-orange-600 to-amber-700 text-white',
    headerText: 'text-amber-950',
    cardBorder: 'border-amber-400',
    fontFamily: 'merriweather',
    badgeStyle: 'bg-amber-600 text-white font-bold px-3 py-0.5 rounded-md shadow-xs border border-amber-300',
    lineColor: '#f59e0b',
    icon: 'Sun',
    bannerGradient: 'from-amber-600 via-orange-600 to-amber-800',
    variant: 'classic_academic',
  },
  modern_sky: {
    id: 'modern_sky',
    name: 'Năng Động Trẻ Trung (Sky Cyan & Teal)',
    badgeTitle: 'Năng Động Trẻ Trung',
    description: 'Nhiều biểu tượng sinh động, chấm chọn phương án A-B-C-D dạng chip tròn hiện đại và sắc sảo.',
    primaryColor: '#0284c7', // sky-600
    primaryBg: '#f0f9ff',
    accentColor: '#0d9488', // teal-600
    headerBg: 'bg-sky-700 text-white',
    headerText: 'text-sky-900',
    cardBorder: 'border-sky-300',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-sky-600 text-white font-semibold px-3 py-1 rounded-full shadow-xs',
    lineColor: '#38bdf8',
    icon: 'Zap',
    bannerGradient: 'from-sky-600 via-teal-600 to-cyan-700',
    variant: 'icon_rich',
  },
  chibi_playful: {
    id: 'chibi_playful',
    name: 'Toán Học Chibi (Chibi Anime Math)',
    badgeTitle: 'Toán Học Chibi',
    description: 'Góc bo tròn mềm mại, hình ảnh Avatar Chibi cô giáo nhí nhảnh, phù hợp cấp 2 và bổ trợ kiến thức.',
    primaryColor: '#d97706', // amber-600
    primaryBg: '#fffbe8',
    accentColor: '#059669', // emerald-600
    headerBg: 'bg-gradient-to-r from-yellow-400 via-amber-500 to-rose-400 text-slate-900',
    headerText: 'text-slate-900',
    cardBorder: 'border-amber-300',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-yellow-400 text-slate-900 font-extrabold px-3 py-1 rounded-2xl shadow-xs border border-amber-500',
    lineColor: '#fbbf24',
    icon: 'Smile',
    bannerGradient: 'from-amber-400 via-yellow-400 to-rose-400',
    variant: 'playful_chibi',
  },
  lesson_plan: {
    id: 'lesson_plan',
    name: 'Giáo Án & Phiếu Chuyên Đề (Teacher Lesson Sheet)',
    badgeTitle: 'Phiếu Chuyên Đề',
    description: 'Bố cục 2 cột chuyên sâu: Khung mục tiêu bài học, tóm tắt lý thuyết trọng tâm, bài tập mẫu và bài rèn luyện.',
    primaryColor: '#334155', // slate-700
    primaryBg: '#f8fafc',
    accentColor: '#2563eb', // blue-600
    headerBg: 'bg-slate-800 text-white',
    headerText: 'text-slate-900',
    cardBorder: 'border-slate-300',
    fontFamily: 'vietnam_pro',
    badgeStyle: 'bg-slate-800 text-white font-bold px-3 py-1 rounded-md shadow-xs',
    lineColor: '#64748b',
    icon: 'FileText',
    bannerGradient: 'from-slate-800 via-slate-700 to-zinc-800',
    variant: 'lesson_sheet',
  },
};
